Repository fawkesrobotics/fawkes, pull requests merged in 2018-11, with the labels that each got.

#12 clips-executive: fix action timeout on nowait action
  src/plugins/clips-executive/clips/domain.clp
Labels: bugfix

#24 Second chunk of fixes for lgtm results
  src/libs/config/net_handler.cpp
  src/libs/config/yaml_node.h
  src/libs/fvcams/firewire.cpp
  src/libs/fvfilters/morphology/morphologicalfilter.h
  src/libs/fvmodels/shape/circle.cpp
  src/libs/fvutils/statistical/histogram_block.cpp
  src/libs/logging/cache.cpp
  src/libs/navgraph/constraints/constraint_repo.cpp
  src/libs/protobuf_comm/client.cpp
  src/libs/protobuf_comm/message_register.cpp
  src/libs/protobuf_comm/server.cpp
  src/plugins/bbsync/bbsync_plugin.cpp
  src/plugins/colli/visualization_thread.cpp
  src/plugins/laser/laser_plugin.cpp
  src/plugins/openni/image_thread.cpp
  src/plugins/pantilt/pantilt_plugin.cpp
  src/plugins/roomba/roombajoy_thread.cpp
  src/plugins/stn-generator/stn-generator_thread.cpp
  src/plugins/xmlrpc/xmlrpc_thread.cpp
  src/tools/plugin_generator/main.cpp
Labels: bugfix, enhancement

#22 Dynamic buildkite pipeline and conditional webview frontend build
  .buildkite/build-webview-frontend
  .buildkite/lint
  .buildkite/pipeline.sh
  .buildkite/pipeline.yml
  .buildkite/steps.d/webview-frontend.sh
  .buildkite/steps.d/webview-frontend.yml
  src/plugins/webview/frontend/Makefile
Labels: enhancement

#25 Master branch push exception and annotation fixes/improvements
  .buildkite/lint
  .buildkite/pipeline.yml
Labels: bugfix, enhancement

#27 laser-filter: fix double free in filter buffer
  src/plugins/laser-filter/filters/filter.cpp
  src/plugins/laser-filter/filters/filter.h
Labels: bugfix
