Repository fawkesrobotics/fawkes, pull requests merged in 2019-03, with the labels that each got.

#55 CX temporal execution monitoring
  cfg/conf.d/clips-executive.yaml
  src/plugins/clips-executive/clips/action-selection/temporal.clp
  src/plugins/clips-executive/clips/execmon/temporal-missed-dispatch.clp
  src/plugins/clips-executive/clips/execmon/temporal-over-duration.clp
  src/plugins/clips-executive/clips/goal.clp
  src/plugins/clips-executive/clips/plan.clp
Labels: enhancement, feature

#66 XABSL plugin fixes
  src/libs/interface/field_pointer.h
  src/lua/skills/generic/fake_relgoto.lua
  src/lua/skills/test.lua
  src/plugins/xabsl/.gitignore
  src/plugins/xabsl/Makefile
  src/plugins/xabsl/XABSL-Soccer.patch
  src/plugins/xabsl/engine_thread.cpp
  src/plugins/xabsl/iface_field_wrapper.h
  src/plugins/xabsl/skill_wrapper.cpp
  src/plugins/xabsl/xabsl_tools.cpp
Labels: bugfix

#56 CEDAR: CLIPS-based Error Detection, Analysis, and Recovery
  cfg/cedar/fawkes-model.clp
  cfg/cedar/ros-model.clp
  cfg/conf.d/cedar.yaml
  src/plugins/Makefile
  src/plugins/cedar/Makefile
  src/plugins/cedar/cedar_plugin.cpp
  src/plugins/cedar/cedar_thread.cpp
  src/plugins/cedar/cedar_thread.h
  src/plugins/cedar/clips/cedar-fawkes.clp
  src/plugins/cedar/clips/cedar-ros.clp
  src/plugins/cedar/clips/cedar.clp
  src/plugins/cedar/clips/fawkes-battery.clp
  src/plugins/cedar/clips/syscond.clp
  src/plugins/cedar/plugin_director_thread.cpp
  src/plugins/cedar/plugin_director_thread.h
Labels: feature

#64 Plexil improvements and blackboard access
  cfg/conf.d/plexil.yaml
  cfg/plexil/external.xml
  src/plugins/plexil/Makefile
  src/plugins/plexil/blackboard_adapter.cpp
  src/plugins/plexil/blackboard_adapter.h
  src/plugins/plexil/plexil_thread.cpp
  src/plugins/plexil/protobuf_adapter.cpp
  src/plugins/plexil/protobuf_adapter.h
  src/plugins/plexil/specs/test/plan.ple
Labels: bugfix, feature

#67 Robot memory renewal of open lock
  src/plugins/clips-executive/clips/coordination-mutex.clp
Labels: bugfix

#68 Fix builds for when there are no other topic branches
  .buildkite/lint
Labels: bugfix

#72 buildkite: fix builds from fork repos
  .buildkite/lint
  .buildkite/pipeline.yml
Labels: bugfix

#70 mongodb_log: Support Debian's mongo/version.h move
  src/plugins/mongodb/mongodb.mk
Labels: bugfix

#74 plexil: fix deadlock in protobuf adapter
  src/plugins/plexil/protobuf_adapter.cpp
Labels: bugfix

#76 gitlint: make subject regex more specific
  .gitlint
Labels: enhancement
