Repository fawkesrobotics/fawkes, pull requests merged in 2019-01, with the labels that each got.

#35 eclipse-clp compile fixes
  src/plugins/eclipse-clp/externals/blackboard.cpp
  src/plugins/eclipse-clp/externals/eclipse_path.cpp
Labels: bugfix

#41 webview-frontend: update dependencies
  src/plugins/webview/frontend/package-lock.json
  src/plugins/webview/frontend/package.json
Labels: enhancement, security

#31 Plexil integration
  cfg/conf.d/navgraph.yaml
  cfg/conf.d/plexil.yaml
  cfg/navgraph-example.yaml
  cfg/plexil/external.xml
  etc/buildsys/openprs.mk
  src/libs/config/yaml.cpp
  src/libs/core/threading/thread.cpp
  src/libs/core/threading/thread.h
  src/libs/interface/message.cpp
  src/libs/utils/misc/map_skill.cpp
  src/libs/utils/misc/map_skill.h
  src/libs/utils/sub_process/proc.cpp
  src/libs/utils/sub_process/proc.h
  src/lua/skiller/fawkes/init.lua
  src/lua/skills/generic/fake_goto.lua
  src/lua/skills/test.lua
  src/plugins/Makefile
  src/plugins/clips-executive/Makefile
  src/plugins/clips-executive/clips_executive_thread.cpp
  src/plugins/navgraph/navgraph_thread.cpp
  src/plugins/plexil/Makefile
  src/plugins/plexil/be_adapter.cpp
  src/plugins/plexil/be_adapter.h
  src/plugins/plexil/clock_adapter.cpp
  src/plugins/plexil/clock_adapter.h
  src/plugins/plexil/config_adapter.cpp
  src/plugins/plexil/config_adapter.h
  src/plugins/plexil/globals_adapter.cpp
  src/plugins/plexil/globals_adapter.h
  src/plugins/plexil/log_adapter.cpp
  src/plugins/plexil/log_adapter.h
  src/plugins/plexil/log_stream.h
  src/plugins/plexil/navgraph_access_thread.cpp
  src/plugins/plexil/navgraph_access_thread.h
  src/plugins/plexil/navgraph_adapter.cpp
  src/plugins/plexil/navgraph_adapter.h
  src/plugins/plexil/plexil.mk
  src/plugins/plexil/plexil_plugin.cpp
  src/plugins/plexil/plexil_thread.cpp
  src/plugins/plexil/plexil_thread.h
  src/plugins/plexil/protobuf_adapter.cpp
  src/plugins/plexil/protobuf_adapter.h
  src/plugins/plexil/remote_adapter.cpp
  src/plugins/plexil/remote_adapter.h
  src/plugins/plexil/specs/.gitignore
  src/plugins/plexil/specs/test/plan.ple
  src/plugins/plexil/thread_adapter.cpp
  src/plugins/plexil/thread_adapter.h
  src/plugins/plexil/timer_thread.cpp
  src/plugins/plexil/timer_thread.h
  src/plugins/plexil/utils.h
Labels: enhancement, feature

#44 Upgrade build pipeline images to Fedora 29
  .buildkite/pipeline.yml
  .buildkite/steps.d/20-webview-frontend.yml
Labels: CI, enhancement

#46 buildkite: account for domain repos for stats generation
  .buildkite/annotations.d/build_stats.sh
Labels: bugfix, buildkite
