Repository fawkesrobotics/fawkes, pull requests merged in 2019-04, with the labels that each got.

#78 Laser Filter: Fix projection calculation for default case
  src/plugins/laser-filter/filters/projection.cpp
Labels: bugfix

#80 Force check before push
  .gitignore
  etc/buildsys/root/check.mk
  etc/buildsys/root/git-hooks.mk
  etc/buildsys/root/root.mk
  etc/git-hooks/pre-push
Labels: feature

#82 realsense: null rs_error_ field after free
  src/plugins/realsense/realsense_thread.cpp
Labels: bugfix

#87 netcomm: do not throw an exception if client is missing or not alive
  src/libs/netcomm/fawkes/server_thread.cpp
Labels: bugfix

#91 Restart realsense if polling fails too often
  cfg/conf.d/realsense.yaml
  src/plugins/realsense/realsense_thread.cpp
  src/plugins/realsense/realsense_thread.h
Labels: enhancement
