Repository fawkesrobotics/fawkes, pull requests merged in 2019-06, with the labels that each got.

#122 Catch all mongocxx exceptions in clips-robot-memory
  src/plugins/clips-executive/clips/wm-robmem-sync.clp
  src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
Labels: bugfix

#123 robot memory: run thread in continuous mode
  src/plugins/robot-memory/Makefile
  src/plugins/robot-memory/computables/computables_manager.cpp
  src/plugins/robot-memory/computables/computables_manager.h
  src/plugins/robot-memory/event_trigger_manager.cpp
  src/plugins/robot-memory/event_trigger_manager.h
  src/plugins/robot-memory/robot_memory.cpp
  src/plugins/robot-memory/robot_memory.h
  src/plugins/robot-memory/robot_memory_thread.cpp
  src/plugins/robot-memory/robot_memory_thread.h
Labels: enhancement

#125 mongodb: make mongod's bind_ip configurable
  src/plugins/mongodb/mongodb_instance_config.cpp
  src/plugins/mongodb/mongodb_instance_config.h
Labels: bugfix

#126 buildsys: expand globs in git ls-files with git, not the shell
  etc/buildsys/format.mk
  etc/buildsys/root/check.mk
  etc/buildsys/root/format.mk
  etc/format-scripts/check-all-files.sh
  etc/format-scripts/check-branch-files.sh
Labels: bugfix

#132 add new realsense2 plugin
  cfg/conf.d/realsense2.yaml
  src/plugins/Makefile
  src/plugins/realsense2/Makefile
  src/plugins/realsense2/realsense2_plugin.cpp
  src/plugins/realsense2/realsense2_thread.cpp
  src/plugins/realsense2/realsense2_thread.h
Labels: feature
