Repository fawkesrobotics/fawkes, pull requests merged in 2020-04, with the labels that each got.

#219 buildkite: fix loop over emails in build creator check
  .buildkite/lint
Labels: buildkite

#221 buildsys: use ldoc instead of luadoc
  etc/buildsys/config.mk
Labels: bugfix

#223 webview-frontend: update dependencies
  src/plugins/webview/frontend/package-lock.json
  src/plugins/webview/frontend/package.json
Labels: dependencies

#224 plugin independent agent config
  cfg/config.yaml
  src/plugins/clips-executive/clips/init.clp
  src/plugins/clips-executive/clips/wm-config.clp
  src/plugins/mongodb_log/mongodb_log_bb_thread.cpp
  src/plugins/mongodb_log/mongodb_log_bb_thread.h
Labels: enhancement
