Repository fawkesrobotics/fawkes, pull requests merged in 2020-02, with the labels that each got.

#192 Rework robotmemory collection dump and restore
  src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
  src/plugins/clips-robot-memory/clips_robot_memory_thread.h
  src/plugins/robot-memory/robot_memory.cpp
  src/plugins/robot-memory/robot_memory.h
Labels: help wanted

#205 Robot memory dump/restore improvements
  src/plugins/robot-memory/Makefile
  src/plugins/robot-memory/robot_memory.cpp
  src/plugins/robot-memory/robot_memory.h
Labels: enhancement

#197 Add skill execution time estimates to the skiller simulator
  cfg/conf.d/skiller-simulator.yaml
  src/plugins/Makefile
  src/plugins/skiller-simulator-navgraph/Makefile
  src/plugins/skiller-simulator-navgraph/navgraph_estimator.cpp
  src/plugins/skiller-simulator-navgraph/navgraph_estimator.h
  src/plugins/skiller-simulator-navgraph/skiller_simulator_navgraph_plugin.cpp
  src/plugins/skiller-simulator-navgraph/skiller_simulator_navgraph_thread.cpp
  src/plugins/skiller-simulator-navgraph/skiller_simulator_navgraph_thread.h
  src/plugins/skiller-simulator/Makefile
  src/plugins/skiller-simulator/estimators/config_estimator.cpp
  src/plugins/skiller-simulator/estimators/config_estimator.h
  src/plugins/skiller-simulator/exec_thread.cpp
  src/plugins/skiller-simulator/exec_thread.h
  src/plugins/skiller-simulator/execution_time_estimator.cpp
  src/plugins/skiller-simulator/execution_time_estimator.h
  src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect.cpp
  src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect.h
  src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect_inifin.cpp
  src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect_inifin.h
  src/plugins/skiller-simulator/tests/Makefile
  src/plugins/skiller-simulator/tests/test_skill_parser.cpp
Labels: feature
